collections:
  news:
    output: true

defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
